#!/bin/sh
<?php
/***************************************************************
*  Copyright notice
*
*  (c) 2004 Michael Stucki (mundaun@gmx.ch)
*  All rights reserved
*
*  This script is part of the TYPO3 project. The TYPO3 project is
*  free software; you can redistribute it and/or modify
*  it under the terms of the GNU General Public License as published by
*  the Free Software Foundation; either version 2 of the License, or
*  (at your option) any later version.
*
*  The GNU General Public License can be found at
*  http://www.gnu.org/copyleft/gpl.html.
*  A copy is found in the textfile GPL.txt and important notices to the license
*  from the author is found in LICENSE.txt distributed with these scripts.
*
*
*  This script is distributed in the hope that it will be useful,
*  but WITHOUT ANY WARRANTY; without even the implied warranty of
*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*  GNU General Public License for more details.
*
*  This copyright notice MUST APPEAR in all copies of the script!
***************************************************************/
/**
 * TYPO3 site installer
 * This script will create new TYPO3 sites.
 *
 * $Id$
 *
 * @author	Sven Wilhelm <wilhelm@icecrash.com>
 * @author	Michael Stucki <mundaun@gmx.ch>
 */

define('INCLUDE_DIR', 'includes/');

// Include the base class and start
require(INCLUDE_DIR.'class.site_installer.php');

$siteInstaller = new site_installer;
$siteInstaller->startUp();

?>